// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHed1ZDa8hYOHDCqb0lHmL0MsUQLu_15E',
    appId: '1:857273564013:web:bc23fb6a0078cd5c747864',
    messagingSenderId: '857273564013',
    projectId: 'uangku-1a837',
    authDomain: 'uangku-1a837.firebaseapp.com',
    storageBucket: 'uangku-1a837.firebasestorage.app',
    measurementId: 'G-MTTMN617KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJLHXTQFFK10sdsqyi_TmPRb2wDbiyzDk',
    appId: '1:857273564013:android:693f41c034edf3e4747864',
    messagingSenderId: '857273564013',
    projectId: 'uangku-1a837',
    storageBucket: 'uangku-1a837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBco-ZqogZh7BNVifVOSTWhSgGbPgNmzA',
    appId: '1:857273564013:ios:16d98d9cf342c4c6747864',
    messagingSenderId: '857273564013',
    projectId: 'uangku-1a837',
    storageBucket: 'uangku-1a837.firebasestorage.app',
    iosBundleId: 'com.example.uangKu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBco-ZqogZh7BNVifVOSTWhSgGbPgNmzA',
    appId: '1:857273564013:ios:16d98d9cf342c4c6747864',
    messagingSenderId: '857273564013',
    projectId: 'uangku-1a837',
    storageBucket: 'uangku-1a837.firebasestorage.app',
    iosBundleId: 'com.example.uangKu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHed1ZDa8hYOHDCqb0lHmL0MsUQLu_15E',
    appId: '1:857273564013:web:23e855f086acb339747864',
    messagingSenderId: '857273564013',
    projectId: 'uangku-1a837',
    authDomain: 'uangku-1a837.firebaseapp.com',
    storageBucket: 'uangku-1a837.firebasestorage.app',
    measurementId: 'G-07DB2QJ8NJ',
  );

}